site_name: Libro IA Agroambiental
theme:
  name: material
  language: es
  features: [content.code.copy, navigation.top, navigation.prev, navigation.next]
  palette:
    - scheme: default
      primary: teal
      accent: indigo

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

extra_css: [stylesheets/extra.css]
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax-config.js

nav:
  - Inicio: index.md
  - estructura-datos.md
  - operaciones-estructuras.md
  - matrices-especiales.md
